sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t klydefrogg/docker-react -f Dockerfile.dev .

script:
  - docker run klydefrogg/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-359031364007"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
    secure: "$AWS_SECRET_ACCESS_KEY"

#something different?
